---

- name: "Rust | Install Cargo"
  shell: "{{ fubarhouse_user_dir }}/.cargo/bin/cargo install {{ item.name }} | cat"
  with_items: "{{ cargo_items }}"
  register: cargo_result
  changed_when: false
  failed_when: cargo_result.rc != 0
  when: item.name is defined
